name: Release CI

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_tests:
    uses: ./.github/workflows/rust.yml
  release:
    runs-on: ubuntu-latest
    needs: build_and_tests
    steps:
      - uses: actions/checkout@v4
      - name: Fetch tags
        run: git fetch --tags --force
      - name: Get current tag annotation
        id: tag-data
        uses: ericcornelissen/git-tag-annotation-action@v2
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v3
        with:
          version_regex: ^v.*
          release_text: ${{ steps.tag-data.outputs.git-tag-annotation }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: failure()
        name: Delete tag
        uses: prompt/actions-delete-tag@v1
